### ISSUE TITLE
How can I use it to benchmark my server hosted on Openshift ? 

### ISSUE THREAD

**Issue by PrateekSonkar** [dwango-js/io-bench#1]
Hey Guys,

Utility of benchmarking works fine when I run it on my local development machine. But give me connection error "connect_error" when I pass url of hosted app on openshift.com.

Could you please help me out how can I use this utility for benchmarking my app hosted on openshift ? Below is command which I used:

c:> io-bench -n 100 -c 10 -m 1000 -R 30 https://qcapp-prateeksonkar.rhcloud.com

Thanks !!
Prateek

**Comment by nkzawa** [comment]
Umm, I have no idea, but the library catches the following error.

`{ [Error: probe error: Error: websocket error] transport: 'websocket' }`

Are you sure that websocket works fine on your environment?

**Comment by PrateekSonkar** [comment]
All of my apps(web/mobile) are able to communicate using socket connection, thanks Nkzawa for your inputs I will investigate this issue.
